const onboardingNodes=[
    {
        name:'start',
        flow:'onboarding',
        uis:[
            {
                type:'text',
                name:'start'
            },
            {
                type:'text',
                name:'askName'
            }
        ],
        transitions:[
            {
                name:'landlord_or_renter',
                function:'saveName',
                flow:'onboarding', 
                node:'landlord_or_renter',
                catchNode:'none'
            }
        ],
        catch:""

    },
    ///////////////////////////////
    {
        name:'landlord_or_renter',
        flow:'onboarding',
        uis:[{
            type:'interactive',
            name:"landlord_or_renter"
        }],
        transitions:[
            {
                name:'learner',
                node:'what_grade_learner',
                function:'isLearner',
                flow:'onboarding', 
                catchNode:'none'
            },
            {
                name:'parent',
                node:'what_grade_parent',
                function:'isParent',
                flow:'onboarding',
                catchNode:'none'
            }
        ],
        catch:""
    },
    ////////////////////////////////////////
    {
        name:'what_grade_learner',
        uis:[{
            type:'text',
            name:"what_grade_learner"
        }],
        transitions:[
            {
                name:'start',
                function:'saveGrade',
                node:'start',
                flow:'learner_questionnaire',
                catchNode:'none'
            }
        ],
        catch:""
    },
      ////////////////////////////////////////
    {
        name:'what_grade_parent',
        uis:[{
            type:'text',
            name:"what_grade_parent"
        }],
        transitions:[
            {
                name:'start',
                function:'saveGrade',
                'node':'start',
                flow:'parent_questionnaire',
                catchNode:'none'
            }
        ],
        catch:""
    }
     
]
 
module.exports={
  onboardingNodes
}