const onboardingNodes=[
    {
        name:'start',
        node:'start',
        flow:'onboarding',
        actions:"none",
        uis:[
            {
                type:'text',
                name:'start'
            },
            {
                type:'text',
                name:'askName'
            }
        ],
        transitions:[
            {
                name:'landlord_or_renter',
                actions:'none',
                flow:'onboarding', 
                node:'landlord_or_renter',
                catchNode:'none',
                triger:""
            }
        ],
        catch:""

    },
    ///////////////////////////////
    {
        name:'landlord_or_renter',
        flow:'onboarding',
        node:'landlord_or_renter',
        actions:"",
        uis:[{
            type:'interactive',
            name:"landlord_or_renter"
        }],
        transitions:[
            {
                name:'askProvince',
                node:'askProvince',
                function:'isLandlord',
                flow:'landlord', 
                catchNode:'none',
                trigger:'landlord'
            },
            {
                name:'askProvince',
                node:'askProvince',
                function:'isRenter',
                flow:'tenant',
                catchNode:'none',
                trugger:'renter'
            }
        ],
        catch:""
    },
   
]
 
module.exports={
  onboardingNodes
}